# Hybrid pipeline: local STT for resilience, OpenAI Realtime for LLM, Deepgram Aura for TTS.
# Requirements:
#   - DEEPGRAM_API_KEY exported or present in config.providers.deepgram.api_key.
#   - OPENAI_API_KEY exported (Realtime + Chat + TTS share the same key by default).
#   - Ensure Deepgram project has Aura voice enabled; audio format Î¼-law 8 kHz.
providers:
  local:
    enable_stt: true
    enable_llm: false
    enable_tts: false
  deepgram:
    api_key: ${DEEPGRAM_API_KEY}
    tts_voice: aura-asteria-en
    tts_format: ulaw
  openai:
    api_key: ${OPENAI_API_KEY}
    realtime_model: gpt-4o-realtime-preview-2024-12-17
    chat_model: gpt-4o-mini
pipelines:
  hybrid_deepgram_openai:
    stt: local_stt
    llm: openai_llm
    tts: deepgram_tts
    options:
      stt:
        locale: en-US
        fallback_chunk_ms: 1500
      llm:
        temperature: 0.4
        max_response_tokens: 256
      tts:
        voice: aura-asteria-en
        format: ulaw
active_pipeline: hybrid_deepgram_openai